name: Code Deployment

on:
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'skipped'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r python/requirements.txt

    - name: Download config.json artifact
      uses: actions/download-artifact@v4
      with:
        name: dor_artifact
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ github.workspace }}/artifacts/

    - name: Run Python script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-north-1"
      run: |
        python3 python/src/download_parse_upload.py artifacts/config.json
