name: Infra Deployment

on:
  push:
    branches:
      - main

env:
  tf_version: '1.9.5'
  tg_version: '0.66.9'
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  AWS_REGION: "eu-north-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Terraform Plugin Cache Dir
      shell: bash
      run: |
          mkdir --parents $TF_PLUGIN_CACHE_DIR

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

    - name: Setup and Deploy S3 in dev with Terragrunt
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_command: 'apply'
        tg_dir: 'terraform/environments/dev/s3'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

    - name: Setup and Deploy CloudFront in dev with Terragrunt
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_command: 'apply'
        tg_dir: 'terraform/environments/dev/cloudfront'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

    - name: Get Terraform Outputs
      id: get_outputs
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_command: 'output -raw bucket_name, cloudfront_domain_name'
        tg_dir: 'terraform/environments/dev/cloudfront'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

    - name: Update config.json with Terraform Outputs
      run: |
        sed -i "s|\"bucket_name\": \"\"|\"bucket_name\": \"${{ steps.get_outputs.outputs.bucket_name }}\"|g" python/src/config.json
        sed -i "s|\"cloudfront_domain\": \"\"|\"cloudfront_domain\": \"${{ steps.get_outputs.outputs.cloudfront_domain_name }}\"|g" python/src/config.json
        sed -i "s|\"cloudfront_url\": \"\"|\"cloudfront_url\": \"https://${{ steps.get_outputs.outputs.cloudfront_domain_name }}/filtered_products.json\"|g" python/src/config.json
