name: Infrastructure Deployment

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: eu-north-1
  ENVIRONMENT: dev
  TF_VERSION: 1.9.5
  TG_VERSION: 0.66.9

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Setup AWS Credentials
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Step 4: Setup Terragrunt
      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v2.1.4
        with:
          TG_VERSION: ${{ env.TG_VERSION }}
          TF_VERSION: ${{ env.TF_VERSION }}


      # Step 5: Check if S3 Bucket Exists
      - name: Check if S3 Bucket Exists
        id: check_s3
        run: |
          BUCKET_NAME="dor-checkpoint-assets-${{ env.ENVIRONMENT }}"
          if aws s3 ls "s3://${BUCKET_NAME}" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Creating S3 bucket ${BUCKET_NAME}"
            terraform -chdir=terraform/environments/${{ env.ENVIRONMENT }}/s3 init
            terraform -chdir=terraform/environments/${{ env.ENVIRONMENT }}/s3 apply -target=aws_s3_bucket.my_bucket -auto-approve
          else
            echo "Bucket ${BUCKET_NAME} already exists"
          fi
        env:
          BUCKET_NAME: dor-checkpoint-assets-${{ env.ENVIRONMENT }}

      # Step 6: Deploy S3 Infrastructure
      - name: Deploy S3 Infrastructure
        run: |
          terraform -chdir=terraform/environments/${{ env.ENVIRONMENT }}/s3 apply -auto-approve

      # Step 7: Update config.json with S3 Bucket Values
      - name: Update config.json with S3 Bucket Values
        run: |
          jq --arg BUCKET_NAME "$BUCKET_NAME" '.bucket_name=$BUCKET_NAME' config.json > tmp.$$.json && mv tmp.$$.json config.json
        env:
          BUCKET_NAME: dor-checkpoint-assets-${{ env.ENVIRONMENT }}

      # Step 8: Check if CloudFront Distribution Exists
      - name: Check if CloudFront Distribution Exists
        id: check_cloudfront
        run: |
          CLOUDFRONT_COMMENT="CloudFront-${{ env.ENVIRONMENT }}"
          CF_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='$CLOUDFRONT_COMMENT'].Id | [0]" --output text)
          if [ -z "$CF_ID" ]; then
            echo "Creating CloudFront distribution"
            terraform -chdir=terraform/environments/${{ env.ENVIRONMENT }}/cloudfront apply -target=aws_cloudfront_distribution.my_distribution -auto-approve
          else
            echo "CloudFront Distribution exists with ID: $CF_ID"
            echo "CF_ID=$CF_ID" >> $GITHUB_ENV
          fi
        env:
          CLOUDFRONT_COMMENT: "CloudFront-${{ env.ENVIRONMENT }}"

      # Step 9: Deploy CloudFront Infrastructure
      - name: Deploy CloudFront Infrastructure
        run: |
          terraform -chdir=terraform/environments/${{ env.ENVIRONMENT }}/cloudfront apply -auto-approve

      # Step 10: Update config.json with CloudFront Values
      - name: Update config.json with CloudFront Values
        run: |
          CF_DOMAIN=$(aws cloudfront get-distribution --id $CF_ID --query "Distribution.DomainName" --output text)
          jq --arg CF_DOMAIN "$CF_DOMAIN" '.cloudfront_domain=$CF_DOMAIN' config.json > tmp.$$.json && mv tmp.$$.json config.json
        env:
          CF_ID: ${{ steps.check_cloudfront.outputs.CF_ID }}

      # Step 11: Backup Terragrunt File
      - name: Backup Terragrunt File
        run: cp terraform/environments/${{ env.ENVIRONMENT }}/cloudfront/terragrunt.hcl terraform/environments/${{ env.ENVIRONMENT }}/cloudfront/terragrunt.hcl.bak

      # Step 12: Cleanup Backup File
      - name: Cleanup Backup File
        if: success()
        run: rm terraform/environments/${{ env.ENVIRONMENT }}/cloudfront/terragrunt.hcl.bak

      # Step 13: Restore Terragrunt File on Failure
      - name: Restore Terragrunt File on Failure
        if: failure()
        run: mv terraform/environments/${{ env.ENVIRONMENT }}/cloudfront/terragrunt.hcl.bak terraform/environments/${{ env.ENVIRONMENT }}/cloudfront/terragrunt.hcl
