name: Infra Deployment

on:
  push:
    branches:
      - main

env:
  tf_version: '1.9.5'
  tg_version: '0.66.9'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.9.5"  # Use a specific, compatible version      

    - name: Setup Terragrunt
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_command: 'apply'
        tg_dir: 'terraform/environments/dev/s3'  # Change this for each specific deployment step

    - name: Deploy S3 in dev
      run: |
        cd terraform/environments/dev/s3
        terragrunt init
        terragrunt apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-north-1"

    - name: Setup Terragrunt for CloudFront
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_command: 'apply'
        tg_dir: 'terraform/environments/dev/cloudfront'  # This is the directory for CloudFront deployment

    - name: Deploy CloudFront in dev
      run: |
        cd terraform/environments/dev/cloudfront
        terragrunt init
        terragrunt apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-north-1"

    - name: Get Terraform Outputs
      id: get_outputs
      run: |
        cd terraform/environments/dev/cloudfront
        echo "bucket_name=$(terragrunt output -raw bucket_name)" >> $GITHUB_ENV
        echo "cloudfront_domain_name=$(terragrunt output -raw cloudfront_domain_name)" >> $GITHUB_ENV

    - name: Update config.json with Terraform Outputs
      run: |
        sed -i "s|\"bucket_name\": \"\"|\"bucket_name\": \"${{ env.bucket_name }}\"|g" python/src/config.json
        sed -i "s|\"cloudfront_domain\": \"\"|\"cloudfront_domain\": \"${{ env.cloudfront_domain_name }}\"|g" python/src/config.json
        sed -i "s|\"cloudfront_url\": \"\"|\"cloudfront_url\": \"https://${{ env.cloudfront_domain_name }}/filtered_products.json\"|g" python/src/config.json
